name: Pipline CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
      - uses: action/setup-node@v3
      - with:
          node-version: 18
      - run: npm install
      - run: npm run test
    depoloy:
      needs: biuld
      run-on: ubuntu-latest
      setps:
      - name: Deploy (simulado ⚠️)
      - run: echo "CI funcionando com GitHub Actions✅! com a API_token = ${{secrets.API_TOKEN}}"